export const Permissions = {
    Psicologo: [
        'PACIENTES_LISTAGEM',
        'SESSOES_AGENDA',
        'PAGAMENTOS_LISTAGEM',
        'PRONTUARIOS_CADASTRO',
        'PRONTUARIOS_LISTAGEM',
        'PRONTUARIOS_EDICAO',
        'HISTORICOS-MEDICOS_CADASTRO',
        'HISTORICOS-MEDICOS_LISTAGEM',
        'HISTORICOS-MEDICOS_EDICAO',
        'HISTORICOS-MEDICOS_EXCLUSAO',
        'DIAGNOSTICOS_CADASTRO',
        'DIAGNOSTICOS_LISTAGEM',
        'DIAGNOSTICOS_EDICAO',
        'PROGRESSOES_CADASTRO',
        'PROGRESSOES_LISTAGEM',
        'PROGRESSOES_EXCLUSAO',
        'PSICOLOGOS_CADASTRO',
        'PSICOLOGOS_LISTAGEM',
        'PSICOLOGOS_EDICAO',
        'RECEPCIONISTAS_CADASTR0',
        'RECEPCIONISTAS_LISTAGEM',
        'RECEPCIONISTAS_EDICAO',
        'RECEPCIONISTAS_EXCLUSAO'
    ],
    Recepcionista: [
        'PACIENTES_REGISTRO',
        'PACIENTES_LISTAGEM',
        'PACIENTES_EDICAO',
        'PACIENTES_EXCLUSAO',
        'SESSOES_AGENDAMENTO',
        'SESSOES_AGENDA',
        'SESSOES_ALTERACOES',
        'PAGAMENTOS_LISTAGEM'
    ]
}